### ISSUE TITLE
Create graph from those vertical lines

### ISSUE THREAD

**Issue by NikolaiT3** [NikolaiT3/452Project5#15]

**Comment by NikolaiT3** [comment]
Graph is uploaded, but it remains untested. The directed/undirected ability during construction should be a big help for our path algorithm

**Comment by NikolaiT3** [comment]
storing works, but it's a completely connected graph - we need to either weight it or store it as not completely connected so we can suss out a path

**Comment by nlonz** [comment]
How is it completely connected? Shouldn't a cell only have an edge to adjacent cells?
