### ISSUE TITLE
Decide how to move from box to box on cell decomposition

### ISSUE THREAD

**Issue by NikolaiT3** [NikolaiT3/452Project5#20]

**Comment by NikolaiT3** [comment]
Comment on method

**Comment by wvance** [comment]
![e9e4dfcc-0808-11e6-9705-377844818ff9](https://cloud.githubusercontent.com/assets/5695201/14752094/d794a7dc-0892-11e6-8221-95fa661763b1.png)

As shown in the picture above, it is possible to create a graph from a given environment. The challenge however, is to move they physical robot through the computed graph. Given a starting point and End Point, we will have the robot move to the closest corner of the given box. This will work for all problems where there is no object aligned on a 'wall'. Given an object on the wall, additional thought is needed to overcome this problem.
