### ISSUE TITLE
Decide cell decomposition method

### ISSUE THREAD

**Issue by NikolaiT3** [NikolaiT3/452Project5#9]
Trapeziodal Decomposition
Morse Cell Decomposition
Visibility Based Decomposition

**Comment by NikolaiT3** [comment]
What if we just ran a Dijkstras and checked each point against forbidden territory, i.e. the square interiors/edges

**Comment by wvance** [comment]
This is the method I believe will be the easiest to program "Vertical Cell Decomposition".  
![screen shot 2016-04-21 at 9 26 23 pm](https://cloud.githubusercontent.com/assets/5695201/14730067/e9e4dfcc-0808-11e6-9705-377844818ff9.png)

**Comment by NikolaiT3** [comment]
We're moving forward with this!
